ecomm/apps/fnd/urls.py
from django.urls import path, include
from ecomm.apps.fnd.views import (
    fnd,
    cart,
    checkout,
    wish,
    comparison,
    category,
    prodtype,
    product,
)

app_name = 'fnd'

urlpatterns = [
    path('', fnd.home, name='home'),
    path('options/', fnd.options, name='options'),
    path('change-language/<str:lang>/', fnd.change_language, name='change_language'),

    path('category/<slug:cat_slug>/products/', category.products, name='category_products'),
    path('product-type/<slug:type_slug>/products/', prodtype.products, name='type_products'),
    path('product/<slug:prod_slug>/', product.show, name='product'),

    path('wish/', include([
        path('', wish.index, name='wish'),
        path('add/', wish.add, name='wish_add'),
        path('delete/', wish.delete, name='wish_delete'),
        path('remove-from-list/<slug:prod_slug>/', wish.remove, name='wish_remove_from_list'),
    ])),

    path('comparison/', include([
        path('', comparison.index, name='comparison'),
        path('add/', comparison.add, name='comparison_add'),
        path('delete/', comparison.delete, name='comparison_delete'),
        path('remove-from-list/<slug:prod_slug>/', comparison.remove, name='comparison_remove_from_list'),
    ])),

    path('cart/', include([
        path('', cart.index, name='cart'),
        path('add/', cart.add, name='cart_add'),
        path('update/', cart.update, name='cart_update'),
        path('delete/', cart.delete, name='cart_delete'),
    ])),

    path('checkout/', include([
        path('', checkout.index, name='checkout'),
        path('update-delivery/', checkout.update_delivery, name='checkout_update_delivery'),
        path('payment-complete/', checkout.payment_complete, name='checkout_payment_complete'),
        path('payment-successful/', checkout.payment_successful, name='checkout_payment_successful'),
    ])),
]

ecomm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import (
    path, 
    include,
    re_path,
)
from django.conf.urls import (
    handler404, 
    handler500, 
    handler403, 
    handler400,
)

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include([
        path('account/', include('ecomm.apps.account.urls', namespace='account')),
        path('', include('ecomm.apps.fnd.urls', namespace='fnd')),
    ])),
    re_path(r'^i18n/', include('django.conf.urls.i18n')),
]

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
        *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
    ]

handler404 = 'ecomm.apps.fnd.views.fnd.error_404'
handler500 = 'ecomm.apps.fnd.views.fnd.error_500'
handler403 = 'ecomm.apps.fnd.views.fnd.error_403'
handler400 = 'ecomm.apps.fnd.views.fnd.error_400'

ecomm/apps/fnd/views/cart.py
from django.views.decorators.http import require_http_methods
from django.utils.translation import gettext_lazy as _
from django.utils.translation import get_language
from django.conf import settings
from django.http import JsonResponse
from django.shortcuts import ( 
    get_object_or_404, 
    render,
    redirect,
)
import json
from ecomm.apps.fnd.utils.cart import Cart
from ecomm.apps.fnd.models import (
    Product,
    Order,
    Delivery,
)



@require_http_methods(['GET'])
def index(request):
    deliveries = Delivery.objs.fnd().valid().shown()
    return render(request, 'apps/fnd/cart.html', {
        'deliveries': deliveries,
    })
 
    
    return redirect('account:dashboard')

@require_http_methods(['POST'])
def add(request):
    cart = Cart(request)
    result = json.loads(request.body)
    item_id = int(result['id'])
    item_quantity = int(result['quantity'])
    product = get_object_or_404(Product, id=item_id)
    cart.add(product=product, quantity=item_quantity)
    cart_filling = len(cart)
    return JsonResponse({'quantity': cart_filling})


@require_http_methods(['POST'])
def update(request):
    cart = Cart(request)
    result = json.loads(request.body)
    item_id = int(result['id'])
    item_quantity = int(result['quantity'])
    cart.update(product=item_id, quantity=item_quantity)
    cart_filling = len(cart)
    cart_total = cart.get_total_price()
    prod_quantity = cart.get_product_quantity(item_id)
    prod_total_price = cart.get_product_total_price(item_id)
    return JsonResponse({
        'id': item_id,
        'quantity': cart_filling, 
        'total_price': cart_total,
        'prod_quantity': prod_quantity,
        'prod_total_price': prod_total_price,
    })


@require_http_methods(['POST'])
def delete(request):
    cart = Cart(request)
    result = json.loads(request.body)
    item_id = int(result['id'])
    cart.delete(product=item_id)
    cart_filling = len(cart)
    cart_total = cart.get_total_price()
    return JsonResponse({
        'id': item_id, 
        'quantity': cart_filling, 
        'total_price': cart_total,
    })

ecomm/apps/fnd/views/category.py
from django.views.decorators.http import require_http_methods
from django.utils.translation import gettext_lazy as _
from django.utils.translation import get_language
from ecomm.vendors.helpers.pagination import with_pagination
from django.db.models import Prefetch
from django.conf import settings
from django.http import JsonResponse
from django.http import Http404
from django.shortcuts import ( 
    get_object_or_404, 
    render,
    redirect,
)
import json
from django.db.models import F
from ecomm.apps.fnd.utils.cart import Cart
from ecomm.vendors.helpers.request import (
    get_filter_arguments,
    get_search_arguments,
)
from ecomm.apps.fnd.models import (
    Category,
    Product,
    ProductType,
    ProductTypeAttribute,
)

@require_http_methods(['GET'])
def products(request, cat_slug):
    current_language = get_language()
    filter_arguments = get_filter_arguments(request)
    search_arguments = get_search_arguments(request)

    category = Category.objs.fnd().valid().shown().\
        filter(slug=cat_slug).\
        prefetch_related(
            Prefetch('types', 
                queryset=ProductType.objs.valid(), 
            )
        ).first()
    if category is None:
        raise Http404

    attrs = ProductTypeAttribute.objs.valid().shown().\
        filter(prod_type__prod__prod_base__category__slug=cat_slug).\
        values(
            slug=F('prod_attribute__slug'), 
            tr=F('prod_attribute__name')
        ).distinct()

    attr_values = Product.objs.fnd().valid().shown().order_by().\
        filter(is_default=True).\
        filter(
            prod_base__category__in=Category.objs.get(slug=cat_slug).get_descendants(include_self=True)
        ).\
        values(
            attr_slug=F('attribute_values__product_attribute__slug'),
            val=F('attribute_values__value'),
            tr=F('attribute_values__trs')
        ).distinct()

    products = Product.objs.valid().shown().\
        filter(is_default=True).\
        filter(
            prod_base__category__in=Category.objs.get(slug=cat_slug).get_descendants(include_self=True)
        ).\
        filter_in_if_args_exists('attribute_values__value__in', filter_arguments).\
        filter_contains_if_args_exists('full_name__icontains', search_arguments).\
        select_related('prod_base').\
        distinct()

    return render(request, 'apps/fnd/category.html', {
        'page_obj': with_pagination(request, products),
        'category': category,
        'attrs': attrs,
        'attr_values': attr_values,
        'filter_arguments': filter_arguments,
        'search_arguments': search_arguments,
    })

ecomm/apps/fnd/views/checkout.py
from django.views.decorators.http import require_http_methods
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required
from django.utils.translation import get_language
from django.conf import settings
from django.http import JsonResponse
from django.shortcuts import (
    get_object_or_404, 
    render,
    redirect,
)
from django.contrib import messages
from ecomm.apps.fnd.models import (
    Delivery,
    Order,
    OrderProduct,
)
import json
from ecomm.apps.fnd.utils.cart import Cart


@require_http_methods(['GET'])
def index(request):
    # Cart in fhd.context.common
    return render(request, 'apps/fnd/checkout.html', {})


#@login_required
@require_http_methods(['POST'])
def update_delivery(request):
    cart = Cart(request)
    result = json.loads(request.body)
    delivery_id = int(result['id'])
    if delivery_id != 0:
        delivery = get_object_or_404(Delivery.objs.fnd().valid().shown(), id=delivery_id)
        cart_total = cart.update_delivery(delivery.price)
        delivery_price = delivery.price
        cart.add_delivery(delivery.id)
    else:
        cart.clear('purchase')
        cart_total = cart.update_delivery()
        delivery_price = 0.0

    return JsonResponse({
        'total_price': cart_total,
        'delivery_price': delivery_price,
    })

# ###
# PayPay
# ###
from paypalcheckoutsdk.orders import OrdersGetRequest
from ecomm.apps.fnd.utils.paypal import PayPalClient
from paypalhttp import HttpError


# @login_required
@require_http_methods(['POST'])
def payment_complete(request):
    PPClient = PayPalClient()

    body = json.loads(request.body)
    data = body['orderID']
    buyer_data = body['buyerData']
    account_id = None

    if request.user.is_authenticated:
        account_id = request.user.id

    try:
        requestorder = OrdersGetRequest(data)
        response = PPClient.client.execute(requestorder)

        total_paid = response.result.purchase_units[0].amount.value
        email = buyer_data['email'] if buyer_data['email'] else response.result.payer.email_address
        address = buyer_data['address'] if buyer_data['address'] else response.result.purchase_units[0].shipping.address.address_line_1
        postal_code = buyer_data['post'] if buyer_data['post'] else response.result.purchase_units[0].shipping.address.postal_code
        country_code = buyer_data['country'] if buyer_data['country'] else response.result.purchase_units[0].shipping.address.country_code
        order_key = response.result.id

        # full_name=response.result.purchase_units[0].shipping.name.full_name,
        # email=response.result.payer.email_address,
        # address=response.result.purchase_units[0].shipping.address.address_line_1,
        # postal_code=response.result.purchase_units[0].shipping.address.postal_code,
        # country_code=response.result.purchase_units[0].shipping.address.country_code,

        cart = Cart(request)
        order = Order.objs.create(
            account_id=account_id,
            email=email,
            address=address,
            postal_code=postal_code,
            country_code=country_code,
            total_paid=total_paid,
            order_key=order_key,
            payment='paypal',
            billing_status=True,
            is_shown=True,
            fnd_id=settings.FND_ALIAS,
        )
        order_id = order.pk

        for item in cart:
            OrderProduct.objs.create(
                order_id=order_id, 
                product_id=item['product']['id'], 
                price=item['price'], 
                quantity=item['quantity'],
                fnd_id=settings.FND_ALIAS,
            )
        return JsonResponse('Payment completed!', safe=False, status=200)
    except:
        return JsonResponse('Payment completed!', safe=False, status=500)

    

#@login_required
def payment_successful(request):
    cart = Cart(request)
    cart.clear()
    messages.success(request, _('Successful payment'))
    return redirect('fnd:home')

ecomm/apps/fnd/views/comparison.py
from django.views.decorators.http import require_http_methods
from django.utils.translation import gettext_lazy as _
from django.utils.translation import get_language
from django.conf import settings
from django.http import JsonResponse
from django.shortcuts import ( 
    get_object_or_404, 
    render,
    redirect,
)
import json
from ecomm.apps.fnd.utils.comparison import Comparison
from ecomm.apps.fnd.models import (
    Product,
    ProductBaseTranslation,
    ProductTypeAttribute,
)


@require_http_methods(['GET'])
def index(request):
    # Comparison in fhd.context.common
    return render(request, 'apps/fnd/compare.html', {})


@require_http_methods(['POST'])
def add(request):
    comparison = Comparison(request)
    result = json.loads(request.body)
    item_id = int(result['id'])
    product = get_object_or_404(Product, id=item_id)
    comparison.add(product.id)
    comparison_filling = len(comparison)
    if request.user.is_authenticated:
        request.user.update_comparison(product.id, 'add')
    return JsonResponse({'quantity': comparison_filling})


@require_http_methods(['POST'])
def delete(request):
    comparison = Comparison(request)
    result = json.loads(request.body)
    item_id = int(result['id'])
    product = get_object_or_404(Product, id=item_id)
    comparison.delete(product.id)
    comparison_filling = len(comparison)
    if request.user.is_authenticated:
        request.user.update_comparison(product.id, 'remove')
    return JsonResponse({'quantity': comparison_filling})


@require_http_methods(['GET'])
def remove(request, prod_slug):
    comparison = Comparison(request)
    product = get_object_or_404(Product, slug=prod_slug)
    comparison.delete(product.id)
    if request.user.is_authenticated:
        request.user.update_comparison(product.id, 'remove')
    return redirect(request.META.get('HTTP_REFERER'))

ecomm/apps/fnd/views/fnd.py
from django.views.decorators.http import require_http_methods
from ecomm.vendors.helpers.pagination import with_pagination
from django.http import JsonResponse
from django.conf import settings
import json
from ecomm.vendors.helpers.request import (
    get_filter_arguments,
    get_search_arguments,
)
from django.shortcuts import (
    render,
    redirect,
)
from django.utils.translation import get_language
from ecomm.apps.fnd.models import (
    Fnd,
    Product,
)



@require_http_methods(['GET'])
def home(request):
    search_arguments = get_search_arguments(request)

    products = Product.objs.fnd().valid().shown().\
        filter(is_default=True).\
        filter_contains_if_args_exists('full_name__icontains', search_arguments).\
        select_related('prod_base')
        
    return render(request, 'apps/fnd/home.html', {
        'page_obj': with_pagination(request, products),
        'search_arguments': search_arguments,
    })


@require_http_methods(['POST'])
def options(request):
    ''' change theme and content_layout  '''
    options = request.session.get('options')
    if 'options' not in request.session:
        options = request.session['options'] = {}

    result = json.loads(request.body)
    settings = result['settings']

    for param in settings:
        options[param['key']] = param['val']
    request.session.modified = True

    return JsonResponse({
        'options': options,
    })


@require_http_methods(['GET'])
def change_language(request, lang=settings.LANGUAGE_CODE):
    if lang in settings.LANGUAGE_CODES:
        request.session['lang'] = lang
    return redirect(request.META.get('HTTP_REFERER'))



# -------------- ERROR PAGES ----------------

@require_http_methods(['GET'])
def error_404(request, *args, **argv):
    data = {}
    return render(request,'apps/fnd/error/404.html', data)

def error_500(request, *args, **argv):
    data = {}
    return render(request,'apps/fnd/error/500.html', data)

def error_403(request, *args, **argv):
    data = {}
    return render(request,'apps/fnd/error/403.html', data)

def error_400(request, *args, **argv):
    data = {}
    return render(request,'apps/fnd/error/400.html', data)

ecomm/apps/fnd/views/product.py
from django.views.decorators.http import require_http_methods
from django.utils.translation import gettext_lazy as _
from django.utils.translation import get_language
from django.conf import settings
from django.http import JsonResponse
from django.shortcuts import ( 
    get_object_or_404, 
    render,
    redirect,
)
from django.db.models import F
from ecomm.apps.fnd.utils.cart import Cart
from ecomm.apps.fnd.models import (
    Category,
    Product,
    ProductTypeAttribute,
)


@require_http_methods(['GET'])
def show(request, prod_slug):
    current_language = get_language()
    product = Product.objs.fnd().valid().shown().\
        filter(slug=prod_slug).\
        prefetch_related('media').\
        select_related('prod_base').\
        first()
    if product is None:
        raise Http404

    attrs = ProductTypeAttribute.objs.filter(prod_type__prod__slug=product.slug).\
        values(
            slug=F('prod_attribute__slug'), 
            name=F('prod_attribute__name')
        ).distinct()

    attr_values = Product.objs.fnd().valid().shown().filter(is_default=True).\
        filter(slug=product.slug).\
        values(
            attr_slug=F('attribute_values__product_attribute__slug'),
            val=F('attribute_values__value'),
            tr=F('attribute_values__trs')
        ).distinct()

    return render(request, 'apps/fnd/product.html', {
        'product': product,
        'attrs': attrs,
        'attr_values': attr_values,
    })

templates/apps/fnd/cart.html
{% extends store.main_layout|default:'layouts/upper.html' %}
{% load static %} 
{% load i18n %}
{% load cart_product_qty %}
{% load or_default_img %}
{% load to_str %}
{% load by_lang %}


{% block content %}
    <div class="flex justify-center">
        {% get_current_language as LANG_CODE %}
        <div class="flex col w-80 p-10">
            <h2 class="text-center my-10">{% translate "Cart" %}</h2>

            <div class="flex my-4 py-4">
                <a class="text-decoration-none text-color" href="{% url 'fnd:home' %}">
                    <span class="border border-color radius-2 pointer py-4 px-8">{% translate "Continue" %}</span>
                </a>
            </div>
            <div class="flex justify-between align-center border border-color radius-2 mb-10">
                <div class="ml-4">
                    <span class="mr-4">{% translate "Items" %}:
                        <span id="cart-quantity">
                            {% with total_qty=cart|length %}
                                {% if total_qty > 0 %}
                                    {{ total_qty }}
                                {% endif %}
                            {% endwith %} 
                        </span>
                    </span>
                    <span class="mr-4">{% translate "Total" %}:
                        <span id="cart-total">{{ cart.get_total_price }}</span>
                    </span>
                    <span class="mr-6">{% translate "Delivery" %}:
                        <span id="cart-delivery">{{ cart.get_delivery_price }}</span>
                    </span>
                </div>
                <div class="flex align-center p-4">
                    <select class="mr-8 p-6" id="deliverySelect" onchange="cart.addDelivery()">
                        <option value="empty" {% if cart.get_delivery_id == 0 %}selected{% endif %}>---</option>
                        {% for delivery in deliveries %}
                            <option value="{{ delivery.id }}" 
                                {% if cart.get_delivery_id == delivery.id %}selected{% endif %}
                            >
                            {{ delivery.get_name_by }}  
                            </option>
                        {% endfor %}
                    </select>
                </div>
                <div class="flex align-center p-4">
                    <a class="text-decoration-none text-color" href="{% url 'fnd:checkout' %}">
                        <button class="border border-color radius-2 pointer py-4 px-8">{% translate "Checkout" %}</button>
                    </a>
                </div>
            </div>
            <div class="flex mt-8 mb-4 text-center">
                <div class="flex-1"></div>
                <div class="flex-2">{% translate "Item" %}</div>
                <div class="flex-1">{% translate "Price" %}</div>
                <div class="flex-1">{% translate "Quantity" %}</div>
                <div class="flex-1">{% translate "Total" %}</div>
                <div class="flex-1"></div>
            </div>
            <hr>

            <div class="flex col my-4">

                {% for item in cart %}
                {% with prod=item.product %}
                <div id="cart-prod-{{ prod.id }}" class="flex align-center border border-color radius-2 p-2 mt-4 cart-item text-center">
                    <div class="flex-2 text-left">
                        <img src="{{ prod.thumb|or_default_img }}">
                    </div>
                    <div class="flex-1 text-left">
                        {{ prod.prod_base.get_name_by }} 
                        <small>
                            {% if prod.ext_name %}
                                ({{ prod.name_ext }})
                            {% endif %}
                        </small>
                    </div>
                    <div class="flex-1">{{ prod.price }}$</div>
                    <div class="flex-1">
                        <div class="flex justify-center align-center">
                            {% cart_product_qty cart prod.id as prod_quantity %}
                            <span onclick="cart.decrement()" data-prodid="{{ prod.id }}">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 16 16">
                                    <path d="m3.86 8.753 5.482 4.796c.646.566 1.658.106 1.658-.753V3.204a1 1 0 0 0-1.659-.753l-5.48 4.796a1 1 0 0 0 0 1.506z"/>
                                </svg>
                            </span>
                            <span id="prod-quantity-{{ prod.id }}" 
                                data-prodid="{{ prod.id }}" 
                                data-quantity="{{ prod_quantity|default_if_none:'' }}">
                                {% cart_product_qty cart prod.id %}
                            </span>
                            <span onclick="cart.increment()" data-prodid="{{ prod.id }}">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 16 16">
                                    <path d="m12.14 8.753-5.482 4.796c-.646.566-1.658.106-1.658-.753V3.204a1 1 0 0 1 1.659-.753l5.48 4.796a1 1 0 0 1 0 1.506z"/>
                                </svg>
                            </span>
                            <button id="update-prod-quantity-btn-{{ prod.id }}" class="border border-clr radius-1 pointer py-1 px-2 hidden">{% translate "Update" %}</button>
                        </div>
                    </div>
                    <div class="flex-1">
                        <span id="prod-total-{{ prod.id }}">{{ item.total_price }}</span>$
                    </div>
                    <div class="flex-1">
                        <button class="border border-color radius-2 pointer py-2 px-4" 
                            onclick="cart.remove()" data-prodid="{{ prod.id }}">
                            {% translate "Delete" %}
                        </button>
                    </div>
                </div>
                {% endwith %}
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock content %} 

templates/apps/fnd/checkout.html
{% extends store.main_layout|default:'layouts/upper.html' %}
{% load static %} 
{% load i18n %}
{% load cart_product_qty %}
{% load or_default_img %}
{% load by_lang %}


{% block content %}
    <div class="flex justify-center">
        {% get_current_language as LANG_CODE %}
        <div class="flex col w-80 p-10">
            <h2 class="text-center my-10">{% translate "Checkout" %}</h2>
            <div class="flex justify-center p-4">
                <div class="flex col p-4 checkout">
                    <div class="flex justify-between my-6">
                        <input class="px-2" type="text" name="order_name" placeholder="{% translate 'Name' %}">
                        <input class="px-2" type="email" name="order_email" placeholder="{% translate 'E-mail' %}">
                    </div>
                    <div class="my-4">{% translate "Shipping information" %}</div>
                    <div class="flex justify-center my-4">
                        <input class="w-full px-2" type="text" name="order_address" placeholder="{% translate 'Address' %}">
                    </div>
                    <div class="flex justify-between my-4">
                        <input class="px-2" type="text" name="order_post" placeholder="{% translate 'Postal code' %}"
                            onkeypress="return onlyZeroToNine(event);"
                        >
                        <input class="px-2" type="text" name="order_country" placeholder="{% translate 'Country code' %}"
                            onkeypress="return onlyZeroToNine(event);"
                        >
                    </div>
                    
                    <div class="flex justify-center my-4">
                        <button id="paypalBtns" 
                            class="border border-color radius-2 pointer text-center w-full my-2 py-2" 
                            onclick="showPayPalBtns()" disabled>
                            {% translate "Continue" %}
                        </button>
                    </div>
                    <div>
                        <div id="paypal-button-container"></div>
                    </div>
                </div>
                <div class="col p-4">
                    <div class="my-6">
                        <a class="text-decoration-none text-color" href="{% url 'fnd:cart' %}">
                            <button class="border border-color radius-2 pointer py-2 px-4">{% translate "Back" %}</button>
                        </a>
                    </div>
                    <div class="my-6">{% translate "Order summary" %}</div>
                    <div class="flex col py-3">
                        
                        {% for item in cart %}
                        {% with prod=item.product %}
                            <div class="flex justify-between align-center my-4 checkout-item">
                                <img src="{{ prod.thumb|or_default_img }}">
                                <div class=" py-2 px-4">
                                    {{ prod.prod_base.get_name_by }} 
                                    <small>
                                        {% if prod.ext_name %}
                                            ({{ prod.name_ext }})
                                        {% endif %}
                                    </small>
                                </div>
                                <div class=" py-2 px-4">{{ item.total_price }}$</div>
                                <div class=" py-2 px-4">{{ item.quantity }}</div>
                            </div>
                        {% endwith %}
                        {% endfor %}

                    </div>
                    <div>
                        {% translate "Items" %}: 
                        {% with total_qty=cart|length %}
                            {% if total_qty > 0 %}
                                {{ total_qty }}
                            {% endif %}
                        {% endwith %} 
                    </div>
                    <div>
                        {% translate "Delivery" %}: 
                        <span id="cart-delivery">{{ cart.get_delivery_price }}</span>
                    </div>
                    <div>{% translate "Total" %}: 
                        <span id="cart-total">{{ cart.get_total_price }}</span>
                    </div>
                </div>

            </div>
        </div>
        
    </div>
{% endblock content %} 

{% block page_script %}
<script src="https://www.paypal.com/sdk/js?client-id=ARq8zA5Dbrdn3elQrn5k97H-NIDJSsDvLzHrqli1e0H2t0vLGyioRm2qwi1K0XGfAo-4_MfsbpeyfLzK"></script>
<script>
    const inputWatchHandler = (condition) => {
        console.log(condition)
        let paypalBtnsContinue = document.querySelector('#paypalBtns');
        let paypalBtnsElem = document.querySelector('#paypal-button-container');
        if (condition) {
            paypalBtnsContinue.disabled = false;
        } else {
            paypalBtnsContinue.disabled = true;
            paypalBtnsElem.innerHTML = '';
        }
    }
    const inputWatcher = new InputWatcher({
        obserEvent: 'keyup',
        obserElementsSelector: '.checkout input',
        handler: inputWatchHandler,
    })
    function initPayPalButtons() {
        const totalPrice = '{{ cart.get_total_price }}';

        const buyerData = {
            'name': document.querySelector('input[name="order_name"]').value,
            'email': document.querySelector('input[name="order_email"]').value,
            'address': document.querySelector('input[name="order_address"]').value,
            'post': document.querySelector('input[name="order_post"]').value,
            'country': document.querySelector('input[name="order_country"]').value,
        }

        paypal.Buttons({
            style: {
                shape: 'rect',
                color: 'gold',
                layout: 'vertical',
                label: 'paypal',
            },
            createOrder: function(data, actions) {
                return actions.order.create({
                    purchase_units: [{
                        amount: {
                            'currency_code': 'USD',
                            'value': parseFloat(totalPrice).toFixed(2),
                        }
                    }]
                });
            },
            onApprove: function(data, actions) {

                var url = '{% url "fnd:checkout_payment_complete" %}'
                return fetch(url, {
                    method: 'POST',
                    headers: { 
                        'Content-Type': 'application/json',
                        'X-CSRFToken': csrftoken,
                    },
                    body: JSON.stringify({
                        orderID: data.orderID,
                        buyerData: buyerData,     
                    })
                })
                .then(function(data) {
                    if (data.status == 200) {
                        location.href = '{% url "fnd:checkout_payment_successful" %}'
                    }
                    if (data.status == 500) {
                        alert('error: order adding to data base');
                    }
                })
            },
        }).render('#paypal-button-container');
    }
    function showPayPalBtns() {
        if (document.querySelector('#paypal-button-container').innerHTML == '') {
            initPayPalButtons();
        }
    }
</script>
{% endblock page_script %} 

templates/apps/fnd/home.html
{% extends fnd.main_layout|default:'layouts/upper.html' %}
{% load static %} 
{% load i18n %}


{% block content %}
    <div class="{{ options.content_layout|default:'list_container-row' }} mt-6 p-8">
        {% for prod in page_obj %}
            {% include 'apps/fnd/partials/product.html' with prod=prod %}
        {% endfor %}
    </div>
    {% include 'partials/pagination.html' %}
{% endblock content %} 