ecomm/apps/fnd/urls.py
from django.urls import path, include
from ecomm.apps.fnd.views import (
    fnd,
    cart,
    checkout,
    wish,
    comparison,
    category,
    prodtype,
    product,
)

app_name = 'fnd'

urlpatterns = [
    path('', fnd.home, name='home'),
    path('options/', fnd.options, name='options'),
    path('change-language/<str:lang>/', fnd.change_language, name='change_language'),

    path('category/<slug:cat_slug>/products/', category.products, name='category_products'),
    path('product-type/<slug:type_slug>/products/', prodtype.products, name='type_products'),
    path('product/<slug:prod_slug>/', product.show, name='product'),

    path('wish/', include([
        path('', wish.index, name='wish'),
        path('add/', wish.add, name='wish_add'),
        path('delete/', wish.delete, name='wish_delete'),
        path('remove-from-list/<slug:prod_slug>/', wish.remove, name='wish_remove_from_list'),
    ])),

    path('comparison/', include([
        path('', comparison.index, name='comparison'),
        path('add/', comparison.add, name='comparison_add'),
        path('delete/', comparison.delete, name='comparison_delete'),
        path('remove-from-list/<slug:prod_slug>/', comparison.remove, name='comparison_remove_from_list'),
    ])),

    path('cart/', include([
        path('', cart.index, name='cart'),
        path('add/', cart.add, name='cart_add'),
        path('update/', cart.update, name='cart_update'),
        path('delete/', cart.delete, name='cart_delete'),
    ])),

    path('checkout/', include([
        path('', checkout.index, name='checkout'),
        path('update-delivery/', checkout.update_delivery, name='checkout_update_delivery'),
        path('payment-complete/', checkout.payment_complete, name='checkout_payment_complete'),
        path('payment-successful/', checkout.payment_successful, name='checkout_payment_successful'),
    ])),
]

ecomm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import (
    path, 
    include,
    re_path,
)
from django.conf.urls import (
    handler404, 
    handler500, 
    handler403, 
    handler400,
)

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include([
        path('account/', include('ecomm.apps.account.urls', namespace='account')),
        path('', include('ecomm.apps.fnd.urls', namespace='fnd')),
    ])),
    re_path(r'^i18n/', include('django.conf.urls.i18n')),
]

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
        *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
    ]

handler404 = 'ecomm.apps.fnd.views.fnd.error_404'
handler500 = 'ecomm.apps.fnd.views.fnd.error_500'
handler403 = 'ecomm.apps.fnd.views.fnd.error_403'
handler400 = 'ecomm.apps.fnd.views.fnd.error_400'

ecomm/apps/fnd/views/cart.py
from django.views.decorators.http import require_http_methods
from django.utils.translation import gettext_lazy as _
from django.utils.translation import get_language
from django.conf import settings
from django.http import JsonResponse
from django.shortcuts import ( 
    get_object_or_404, 
    render,
    redirect,
)
import json
from ecomm.apps.fnd.utils.cart import Cart
from ecomm.apps.fnd.models import (
    Product,
    Order,
    Delivery,
)



@require_http_methods(['GET'])
def index(request):
    deliveries = Delivery.objs.fnd().valid().shown()
    return render(request, 'apps/fnd/cart.html', {
        'deliveries': deliveries,
    })
 
    
    return redirect('account:dashboard')

@require_http_methods(['POST'])
def add(request):
    cart = Cart(request)
    result = json.loads(request.body)
    item_id = int(result['id'])
    item_quantity = int(result['quantity'])
    product = get_object_or_404(Product, id=item_id)
    cart.add(product=product, quantity=item_quantity)
    cart_filling = len(cart)
    return JsonResponse({'quantity': cart_filling})


@require_http_methods(['POST'])
def update(request):
    cart = Cart(request)
    result = json.loads(request.body)
    item_id = int(result['id'])
    item_quantity = int(result['quantity'])
    cart.update(product=item_id, quantity=item_quantity)
    cart_filling = len(cart)
    cart_total = cart.get_total_price()
    prod_quantity = cart.get_product_quantity(item_id)
    prod_total_price = cart.get_product_total_price(item_id)
    return JsonResponse({
        'id': item_id,
        'quantity': cart_filling, 
        'total_price': cart_total,
        'prod_quantity': prod_quantity,
        'prod_total_price': prod_total_price,
    })


@require_http_methods(['POST'])
def delete(request):
    cart = Cart(request)
    result = json.loads(request.body)
    item_id = int(result['id'])
    cart.delete(product=item_id)
    cart_filling = len(cart)
    cart_total = cart.get_total_price()
    return JsonResponse({
        'id': item_id, 
        'quantity': cart_filling, 
        'total_price': cart_total,
    })

ecomm/apps/fnd/views/category.py
from django.views.decorators.http import require_http_methods
from django.utils.translation import gettext_lazy as _
from django.utils.translation import get_language
from ecomm.vendors.helpers.pagination import with_pagination
from django.db.models import Prefetch
from django.conf import settings
from django.http import JsonResponse
from django.http import Http404
from django.shortcuts import ( 
    get_object_or_404, 
    render,
    redirect,
)
import json
from django.db.models import F
from ecomm.apps.fnd.utils.cart import Cart
from ecomm.vendors.helpers.request import (
    get_filter_arguments,
    get_search_arguments,
)
from ecomm.apps.fnd.models import (
    Category,
    Product,
    ProductType,
    ProductTypeAttribute,
)

@require_http_methods(['GET'])
def products(request, cat_slug):
    current_language = get_language()
    filter_arguments = get_filter_arguments(request)
    search_arguments = get_search_arguments(request)

    category = Category.objs.fnd().valid().shown().\
        filter(slug=cat_slug).\
        prefetch_related(
            Prefetch('types', 
                queryset=ProductType.objs.valid(), 
            )
        ).first()
    if category is None:
        raise Http404

    attrs = ProductTypeAttribute.objs.valid().shown().\
        filter(prod_type__prod__prod_base__category__slug=cat_slug).\
        values(
            slug=F('prod_attribute__slug'), 
            tr=F('prod_attribute__name')
        ).distinct()

    attr_values = Product.objs.fnd().valid().shown().order_by().\
        filter(is_default=True).\
        filter(
            prod_base__category__in=Category.objs.get(slug=cat_slug).get_descendants(include_self=True)
        ).\
        values(
            attr_slug=F('attribute_values__product_attribute__slug'),
            val=F('attribute_values__value'),
            tr=F('attribute_values__trs')
        ).distinct()

    products = Product.objs.valid().shown().\
        filter(is_default=True).\
        filter(
            prod_base__category__in=Category.objs.get(slug=cat_slug).get_descendants(include_self=True)
        ).\
        filter_in_if_args_exists('attribute_values__value__in', filter_arguments).\
        filter_contains_if_args_exists('full_name__icontains', search_arguments).\
        select_related('prod_base').\
        distinct()

    return render(request, 'apps/fnd/category.html', {
        'page_obj': with_pagination(request, products),
        'category': category,
        'attrs': attrs,
        'attr_values': attr_values,
        'filter_arguments': filter_arguments,
        'search_arguments': search_arguments,
    })

ecomm/apps/fnd/views/checkout.py
from django.views.decorators.http import require_http_methods
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required
from django.utils.translation import get_language
from django.conf import settings
from django.http import JsonResponse
from django.shortcuts import (
    get_object_or_404, 
    render,
    redirect,
)
from django.contrib import messages
from ecomm.apps.fnd.models import (
    Delivery,
    Order,
    OrderProduct,
)
import json
from ecomm.apps.fnd.utils.cart import Cart


@require_http_methods(['GET'])
def index(request):
    # Cart in fhd.context.common
    return render(request, 'apps/fnd/checkout.html', {})


#@login_required
@require_http_methods(['POST'])
def update_delivery(request):
    cart = Cart(request)
    result = json.loads(request.body)
    delivery_id = int(result['id'])
    if delivery_id != 0:
        delivery = get_object_or_404(Delivery.objs.fnd().valid().shown(), id=delivery_id)
        cart_total = cart.update_delivery(delivery.price)
        delivery_price = delivery.price
        cart.add_delivery(delivery.id)
    else:
        cart.clear('purchase')
        cart_total = cart.update_delivery()
        delivery_price = 0.0

    return JsonResponse({
        'total_price': cart_total,
        'delivery_price': delivery_price,
    })

# ###
# PayPay
# ###
from paypalcheckoutsdk.orders import OrdersGetRequest
from ecomm.apps.fnd.utils.paypal import PayPalClient
from paypalhttp import HttpError


# @login_required
@require_http_methods(['POST'])
def payment_complete(request):
    PPClient = PayPalClient()

    body = json.loads(request.body)
    data = body['orderID']
    buyer_data = body['buyerData']
    account_id = None

    if request.user.is_authenticated:
        account_id = request.user.id

    try:
        requestorder = OrdersGetRequest(data)
        response = PPClient.client.execute(requestorder)

        total_paid = response.result.purchase_units[0].amount.value
        email = buyer_data['email'] if buyer_data['email'] else response.result.payer.email_address
        address = buyer_data['address'] if buyer_data['address'] else response.result.purchase_units[0].shipping.address.address_line_1
        postal_code = buyer_data['post'] if buyer_data['post'] else response.result.purchase_units[0].shipping.address.postal_code
        country_code = buyer_data['country'] if buyer_data['country'] else response.result.purchase_units[0].shipping.address.country_code
        order_key = response.result.id

        # full_name=response.result.purchase_units[0].shipping.name.full_name,
        # email=response.result.payer.email_address,
        # address=response.result.purchase_units[0].shipping.address.address_line_1,
        # postal_code=response.result.purchase_units[0].shipping.address.postal_code,
        # country_code=response.result.purchase_units[0].shipping.address.country_code,

        cart = Cart(request)
        order = Order.objs.create(
            account_id=account_id,
            email=email,
            address=address,
            postal_code=postal_code,
            country_code=country_code,
            total_paid=total_paid,
            order_key=order_key,
            payment='paypal',
            billing_status=True,
            is_shown=True,
            fnd_id=settings.FND_ALIAS,
        )
        order_id = order.pk

        for item in cart:
            OrderProduct.objs.create(
                order_id=order_id, 
                product_id=item['product']['id'], 
                price=item['price'], 
                quantity=item['quantity'],
                fnd_id=settings.FND_ALIAS,
            )
        return JsonResponse('Payment completed!', safe=False, status=200)
    except:
        return JsonResponse('Payment completed!', safe=False, status=500)

    

#@login_required
def payment_successful(request):
    cart = Cart(request)
    cart.clear()
    messages.success(request, _('Successful payment'))
    return redirect('fnd:home')

ecomm/apps/fnd/views/comparison.py
from django.views.decorators.http import require_http_methods
from django.utils.translation import gettext_lazy as _
from django.utils.translation import get_language
from django.conf import settings
from django.http import JsonResponse
from django.shortcuts import ( 
    get_object_or_404, 
    render,
    redirect,
)
import json
from ecomm.apps.fnd.utils.comparison import Comparison
from ecomm.apps.fnd.models import (
    Product,
    ProductBaseTranslation,
    ProductTypeAttribute,
)


@require_http_methods(['GET'])
def index(request):
    # Comparison in fhd.context.common
    return render(request, 'apps/fnd/compare.html', {})


@require_http_methods(['POST'])
def add(request):
    comparison = Comparison(request)
    result = json.loads(request.body)
    item_id = int(result['id'])
    product = get_object_or_404(Product, id=item_id)
    comparison.add(product.id)
    comparison_filling = len(comparison)
    if request.user.is_authenticated:
        request.user.update_comparison(product.id, 'add')
    return JsonResponse({'quantity': comparison_filling})


@require_http_methods(['POST'])
def delete(request):
    comparison = Comparison(request)
    result = json.loads(request.body)
    item_id = int(result['id'])
    product = get_object_or_404(Product, id=item_id)
    comparison.delete(product.id)
    comparison_filling = len(comparison)
    if request.user.is_authenticated:
        request.user.update_comparison(product.id, 'remove')
    return JsonResponse({'quantity': comparison_filling})


@require_http_methods(['GET'])
def remove(request, prod_slug):
    comparison = Comparison(request)
    product = get_object_or_404(Product, slug=prod_slug)
    comparison.delete(product.id)
    if request.user.is_authenticated:
        request.user.update_comparison(product.id, 'remove')
    return redirect(request.META.get('HTTP_REFERER'))

ecomm/apps/fnd/views/fnd.py
from django.views.decorators.http import require_http_methods
from ecomm.vendors.helpers.pagination import with_pagination
from django.http import JsonResponse
from django.conf import settings
import json
from ecomm.vendors.helpers.request import (
    get_filter_arguments,
    get_search_arguments,
)
from django.shortcuts import (
    render,
    redirect,
)
from django.utils.translation import get_language
from ecomm.apps.fnd.models import (
    Fnd,
    Product,
)



@require_http_methods(['GET'])
def home(request):
    search_arguments = get_search_arguments(request)

    products = Product.objs.fnd().valid().shown().\
        filter(is_default=True).\
        filter_contains_if_args_exists('full_name__icontains', search_arguments).\
        select_related('prod_base')
        
    return render(request, 'apps/fnd/home.html', {
        'page_obj': with_pagination(request, products),
        'search_arguments': search_arguments,
    })


@require_http_methods(['POST'])
def options(request):
    ''' change theme and content_layout  '''
    options = request.session.get('options')
    if 'options' not in request.session:
        options = request.session['options'] = {}

    result = json.loads(request.body)
    settings = result['settings']

    for param in settings:
        options[param['key']] = param['val']
    request.session.modified = True

    return JsonResponse({
        'options': options,
    })


@require_http_methods(['GET'])
def change_language(request, lang=settings.LANGUAGE_CODE):
    if lang in settings.LANGUAGE_CODES:
        request.session['lang'] = lang
    return redirect(request.META.get('HTTP_REFERER'))



# -------------- ERROR PAGES ----------------

@require_http_methods(['GET'])
def error_404(request, *args, **argv):
    data = {}
    return render(request,'apps/fnd/error/404.html', data)

def error_500(request, *args, **argv):
    data = {}
    return render(request,'apps/fnd/error/500.html', data)

def error_403(request, *args, **argv):
    data = {}
    return render(request,'apps/fnd/error/403.html', data)

def error_400(request, *args, **argv):
    data = {}
    return render(request,'apps/fnd/error/400.html', data)

ecomm/apps/fnd/views/product.py
from django.views.decorators.http import require_http_methods
from django.utils.translation import gettext_lazy as _
from django.utils.translation import get_language
from django.conf import settings
from django.http import JsonResponse
from django.shortcuts import ( 
    get_object_or_404, 
    render,
    redirect,
)
from django.db.models import F
from ecomm.apps.fnd.utils.cart import Cart
from ecomm.apps.fnd.models import (
    Category,
    Product,
    ProductTypeAttribute,
)


@require_http_methods(['GET'])
def show(request, prod_slug):
    current_language = get_language()
    product = Product.objs.fnd().valid().shown().\
        filter(slug=prod_slug).\
        prefetch_related('media').\
        select_related('prod_base').\
        first()
    if product is None:
        raise Http404

    attrs = ProductTypeAttribute.objs.filter(prod_type__prod__slug=product.slug).\
        values(
            slug=F('prod_attribute__slug'), 
            name=F('prod_attribute__name')
        ).distinct()

    attr_values = Product.objs.fnd().valid().shown().filter(is_default=True).\
        filter(slug=product.slug).\
        values(
            attr_slug=F('attribute_values__product_attribute__slug'),
            val=F('attribute_values__value'),
            tr=F('attribute_values__trs')
        ).distinct()

    return render(request, 'apps/fnd/product.html', {
        'product': product,
        'attrs': attrs,
        'attr_values': attr_values,
    })

templates/apps/fnd/partials/product.html
{% load static %} 
{% load i18n %}
{% load to_str %}
{% load cart_product_qty %}
{% load or_default_img %}


<div class="border border-color radius-2 m-8 p-4 product">
    <img src="{{ prod.thumbUrl }}">
    <div class="data">
        <div class="cont">
            <span class="title">
                {{ prod.prod_base.get_name_by }} 
                <small>
                    {% if prod.ext_name %}
                        ({{ prod.name_ext }})
                    {% endif %}
                </small>
            </span>
            <span class="price">
                {% if prod.sale_price %}
                    <small>(<s>{{ prod.price }}</s>)</small>{{ prod.sale_price }}
                {% else %}
                    {{ prod.price }}
                {% endif %}
            </span>
            <div class="acts my-4">
                <div class="act relative">
                    <div class="absolute full" onclick="wish.toggle()" data-prodid="{{ prod.id }}">
                        <svg class="prod-wish {% if prod.id|to_str in wish.get_product_ids %}wished{% endif %}" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" 
                            stroke="currentColor"
                            stroke-width="1"
                            stroke-linecap="round" stroke-linejoin="round" fill="transparent">
                            <path d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" />
                        </svg>
                    </div>
                </div>
                <!--
                <div class="act relative">
                    <div class="absolute full w-80 t-2" onclick="compare.toggle()" data-prodid="{{ prod.id }}">
                        <svg class="prod-compare {% if prod.id|to_str in comparison.get_product_ids %}compared{% endif %}"  xmlns="http://www.w3.org/2000/svg" 
                            viewBox="0 0 16 16" 
                            stroke="currentColor"
                            stroke-width="1"
                            stroke-linecap="round" stroke-linejoin="round" fill="transparent">
                            <path fill-rule="nonzero" d="M1 1 L1 15 L15 15 L15 1 L1 1"/>
                        </svg>
                    </div>
                </div>-->
                <div class="act relative">
                    <div class="absolute full w-80 t-2" onclick="compare.toggle()" data-prodid="{{ prod.id }}">
                        <svg class="prod-compare {% if prod.id|to_str in comparison.get_product_ids %}compared{% endif %}" 
                            xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256"
                            stroke="currentColor"
                            stroke-width="1"
                            stroke-linecap="round" stroke-linejoin="round" fill="transparent">
                            <rect fill="none"></rect>
                            <line x1="128" y1="40" x2="128" y2="216" stroke-linejoin="round" stroke-width="12"></line>
                            <line x1="104" y1="216" x2="152" y2="216" stroke-linejoin="round" stroke-width="12"></line>
                            <line x1="56" y1="88" x2="200" y2="56" stroke-linecap="round" stroke-linejoin="round" stroke-width="12"></line>
                            <path d="M24,168c0,17.7,20,24,32,24s32-6.3,32-24L56,88Z" stroke-linecap="round" stroke-linejoin="round" stroke-width="12"></path>
                            <path d="M168,136c0,17.7,20,24,32,24s32-6.3,32-24L200,56Z" stroke-linecap="round" stroke-linejoin="round" stroke-width="12"></path>
                        </svg>
                    </div>
                </div>

            </div>
            <div class="btns">
                <div class="flex align-center">
                    {% cart_product_qty cart prod.id as prod_quantity %}
                    <button onclick="cart.select()" 
                        data-prodid="{{ prod.id }}" 
                        data-quantity="{{ prod_quantity|default_if_none:'' }}"  
                        class="relative border border-color text-color radius-2 pointer px-4 mr-2
                        {% if prod.id in cart.get_product_ids %}prod-selected{% endif %}
                    ">
                        <div class="absolute prod-count 
                            {% if not prod_quantity %}hidden{% endif %}
                            ">
                            <small>{{ prod_quantity|default_if_none:'' }}</small>
                        </div>
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor">
                            <path d="M9 5.5a.5.5 0 0 0-1 0V7H6.5a.5.5 0 0 0 0 1H8v1.5a.5.5 0 0 0 1 0V8h1.5a.5.5 0 0 0 0-1H9V5.5z"/>
                            <path d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1H.5zm3.915 10L3.102 4h10.796l-1.313 7h-8.17zM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0z"/>
                        </svg>
                    </button>
                    <button class="border border-color text-color radius-2 pointer px-4 mr-2"
                        onclick='location.href="{% url "fnd:product" prod.slug %}"'>
                        {% translate "View" %}
                    </button>
                </div>
            </div>
            <div class="info">
                {{ prod.prod_base.short_desc }}
            </div>
        </div>
    </div>
</div>