ecomm/apps/account/urls.py
from django.urls import path, include
from ecomm.apps.account.views import (
	address,
	dashboard,
	orders,
	reset,
	auth,
)


app_name = 'account'

urlpatterns = [
	path('dashboard/', dashboard.index, name='dashboard'),
	path('orders/', orders.index, name='orders'),

	path('signin/', auth.signin, name='signin'),
	path('entry/', auth.entry, name='entry'),
	path('signup/', auth.signup, name='signup'),
	path('registration/', auth.registration, name='registration'),
	path('signout/', auth.signout, name='signout'),
	path('activate/<slug:uidb64>/<slug:token>/', auth.account_activate, name='activate'),

	path('address/', include([
        path('list/', address.index, name='address_list'),
		# path('create/', address.create, name='address_create'),
		# path('store/', address.store, name='address_store'),
		path('edit/<int:pk>/', address.edit, name='address_edit'),
		path('update/', address.update, name='address_update'),
		path('destroy/<int:pk>/', address.destroy, name='address_destroy'),
		path('set-default/<int:pk>/', address.set_default, name='address_set_default'),
    ])),

	path('reset-passwd/', include([
		path('create', reset.reset_passwd_create, name='reset_passwd_create'),
		path('mail', reset.reset_passwd_mail, name='reset_passwd_mail'),
	])),

	path('confirm-passwd/', include([
		path('create', reset.confirm_passwd_create, name='confirm_passwd_create'),
		path('store', reset.confirm_passwd_store, name='confirm_passwd_store'),
		path('from-mail/<slug:uidb64>/<slug:token>/', reset.confirm_passwd_from_mail, name='confirm_passwd_from_mail'),
	])),
]

ecomm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import (
    path, 
    include,
    re_path,
)
from django.conf.urls import (
    handler404, 
    handler500, 
    handler403, 
    handler400,
)

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include([
        path('account/', include('ecomm.apps.account.urls', namespace='account')),
        path('', include('ecomm.apps.fnd.urls', namespace='fnd')),
    ])),
    re_path(r'^i18n/', include('django.conf.urls.i18n')),
]

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
        *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
    ]

handler404 = 'ecomm.apps.fnd.views.fnd.error_404'
handler500 = 'ecomm.apps.fnd.views.fnd.error_500'
handler403 = 'ecomm.apps.fnd.views.fnd.error_403'
handler400 = 'ecomm.apps.fnd.views.fnd.error_400'

ecomm/apps/account/models/account.py
from django.db import models
from django.conf import settings
from django.utils.encoding import force_str
from django.utils.http import urlsafe_base64_decode
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import AbstractUser
from ecomm.vendors.base.model import BaseModel
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType
from ecomm.vendors.mixins.model import (
	SoftdeleteMixin, 
	TimestampsMixin,
)

class Account(AbstractUser, BaseModel, TimestampsMixin, SoftdeleteMixin):
    fnds = models.JSONField(
        null=True, 
        blank=True
    )
    wish = models.JSONField(
        null=True, 
        blank=True,
    )
    comparison = models.JSONField(
        null=True, 
        blank=True,
    )
    
    class Meta:
        verbose_name =  _('Account')
        verbose_name_plural =  _('Accounts')
        permissions = [
            ('view_dashboard', 'View Dasboard page'),
            ('view_orders', 'View orders page'),
        ]

    def __str__(self):
        return self.username

    @classmethod
    def get_by_uid(cls, uidb64):
        try:
            uid = force_str(urlsafe_base64_decode(uidb64)) 
            user = cls.objs.get(pk=uid)
        except(TypeError, ValueError, OverflowError, user.DoesNotExist):
            user = None
        return user


    def get_wish(self, alias=settings.FND_ALIAS):
        try:
            return self.wish[alias]
        except:
            return []

    def get_comparison(self, alias=settings.FND_ALIAS):
        try:
            return self.comparison[alias]
        except:
            return []

    def update_wish(self, prod_id, key='add', alias=settings.FND_ALIAS):
        if key == 'add':
            if self.wish:
                self.wish.append(str(prod_id))
            else:
                self.wish = [str(prod_id)]
        elif key == 'remove':
            if self.wish:
                self.wish.remove(str(prod_id))
        self.save(update_fields=['wish'])

    def update_comparison(self, prod_id, key='add', alias=settings.FND_ALIAS):
        if key == 'add':
            if self.comparison:
                self.comparison.append(str(prod_id))
            else:
                self.comparison = [str(prod_id)]
        elif key == 'remove':
            if self.comparison:
                self.comparison.remove(str(prod_id))
        self.save(update_fields=['comparison'])

    def account_permissions(self):
        content_type = ContentType.objects.get_for_model(Account)
        # permission = Permission.objects.get(
        #     codename='view_dashboard',
        #     content_type=content_type,
        # )
        accont_perms = Permission.objects.filter(content_type=content_type)
        for perm in accont_perms:
            self.user_permissions.add(perm)

ecomm/apps/account/models/address.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from ecomm.vendors.base.model import BaseModel
from django.contrib.auth import get_user_model
Account = get_user_model()


class Address(BaseModel):
	full_name = models.CharField(
		_('Full Name'), 
		max_length=150
	)
	phone = models.CharField(
		_('Phone Number'), 
		max_length=50,
		null=True,
		blank=True
	)
	postcode = models.CharField(
		_('Postcode'), 
		max_length=50
	)
	address_line = models.CharField(
		_('Address Line'), 
		max_length=255
	)
	town_city = models.CharField(
		_('Town/City/State'), 
		max_length=150
	)
	delivery_instructions = models.CharField(
		_('Delivery Instructions'), 
		max_length=255
	)
	default = models.BooleanField(
		_('Default'), 
		default=False
	)
	account = models.ForeignKey(
		Account, 
		verbose_name=_('Account'), 
		on_delete=models.CASCADE
	)

	class Meta:
		verbose_name = _('Address')
		verbose_name_plural = _('Addresses')

	def __str__(self):
		return '{} Address'.format(self.full_name)

ecomm/apps/account/models/profile.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import get_user_model
Account = get_user_model()

def profile_photo_upload_to(instance, filename):
	return f'account/{instance.id}/photo/{filename}'

class Profile(models.Model):
	MALE = 'male'
	FEMALE = 'female'

	SEX_CHOICES = [
		(MALE,   _('Male')),
		(FEMALE, _('Female')),
	]

	account = models.OneToOneField(
		Account, 
		on_delete=models.CASCADE
	)
	photo = models.ImageField(
		upload_to=profile_photo_upload_to, 
		null=True, 
		blank=True
	)
	phone = models.CharField(
		max_length=25, 
		null=True, 
		blank=True
	)
	age = models.IntegerField(
		null=True, 
		blank=True
	)
	birthdate = models.DateField(
		null=True, 
		blank=True
	)
	sex = models.CharField(
		max_length=8, 
		choices=SEX_CHOICES, 
		default=MALE
	)

	class Meta:
		verbose_name = _('Profile')
		verbose_name_plural = _('Profiles')

ecomm/apps/fnd/models/order.py
from django.db import models
from django.conf import settings
from django.utils.translation import gettext_lazy as _
from ecomm.vendors.base.model import BaseModel
from ecomm.vendors.mixins.model import (
	SoftdeleteMixin, 
	TimestampsMixin,
)
from django.contrib.auth import get_user_model
Account = get_user_model()



class Order(BaseModel, TimestampsMixin, SoftdeleteMixin):
	account = models.ForeignKey(
		Account, 
		on_delete=models.CASCADE, 
		related_name='order_account',
		null=True, 
		blank=True,
	)
	email = models.EmailField(
		max_length=254, blank=True
	)
	address = models.CharField(
		max_length=250
	)
	city = models.CharField(
		max_length=100
	)
	phone = models.CharField(
		max_length=100
	)
	postal_code = models.CharField(
		max_length=20
	)
	country_code = models.CharField(
		max_length=4, 
		blank=True
	)
	total_paid = models.DecimalField(
		max_digits=5, 
		decimal_places=2
	)
	order_key = models.CharField(
		max_length=200
	)
	billing_status = models.BooleanField(
		default=False
	)
	payment = models.CharField( # 'paypal'
		max_length=200, 
		blank=True,
	)
	fnd = models.ForeignKey(
		'Fnd',
		on_delete=models.CASCADE, 
		related_name='fnd_orders',
	)

	class Meta:
		verbose_name = _('Order')
		verbose_name_plural = _('Orders')
		ordering = ('-created_at',)

	def __str__(self):
		return str(self.order_key)

	list_values = [
		'order_key', 
		'total_paid',  
		'address__full_name', 
		'created_at'
	]


class OrderProduct(BaseModel):
	order = models.ForeignKey(
		Order, 
		related_name='order_orderproducts', 
		on_delete=models.CASCADE
	)
	product = models.ForeignKey(
		'Product', 
		related_name='prod_orderproducts', 
		on_delete=models.CASCADE
	)
	price = models.DecimalField(
		max_digits=5, 
		decimal_places=2
	)
	quantity = models.PositiveIntegerField(
		default=1
	)
	fnd = models.ForeignKey(
		'Fnd',
		on_delete=models.CASCADE, 
		related_name='fnd_order_products',
	)

	def __str__(self):
		return str(self.id)

ecomm/apps/account/forms/account.py
from django import forms
from django.conf import settings
from django.utils.translation import gettext_lazy as _
from ecomm.vendors.helpers.validators import email_validation_check
from django.contrib.auth.forms import (
	PasswordResetForm,
	SetPasswordForm,
)
from ecomm.apps.account.models import Account


class PwdResetForm(PasswordResetForm):
	email = forms.EmailField(
		max_length=254,
		widget=forms.TextInput(
			attrs={'class': 'border border-color radius-2 p-4', 'placeholder': _('Email'), 'id': 'form-email'}
		))
	def clean_email(self):
		email = self.cleaned_data['email']
		email_validation_check(email)
		u = Account.objs.filter(email=email)
		if not u:
			raise forms.ValidationError(
				_('Unfortunatley we can not find that email address'))
		return email


class PwdResetConfirmForm(SetPasswordForm):
	new_password1 = forms.CharField(
		label=_('New password'), 
		widget=forms.PasswordInput(
			attrs={'class': 'border border-color radius-2 p-4', 'placeholder': _('New Password'), 'id': 'form-newpass'}
		))
	new_password2 = forms.CharField(
		label=_('Repeat password'), 
		widget=forms.PasswordInput(
			attrs={'class': 'border border-color radius-2 p-4', 'placeholder': _('New Password'), 'id': 'form-new-pass2'}
		))

	def clean_new_password2(self):
		new_passwd1 = self.cleaned_data['new_password1']
		new_passwd2 = self.cleaned_data['new_password2']
		if new_passwd1 != new_passwd2:
			raise forms.ValidationError(
				_('Passwords are not equal'))
		return new_passwd1

ecomm/apps/account/forms/address.py
from django import forms
from ecomm.apps.account.models import Address


class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = [
        	'full_name', 
        	'phone', 
        	'address_line', 
        	'town_city', 
        	'postcode'
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['full_name'].widget.attrs.update(
            {'class': '', 'placeholder': 'Full Name'}
        )
        self.fields['phone'].widget.attrs.update(
        	{'class': '', 'placeholder': 'Phone'}
        )
        self.fields['address_line'].widget.attrs.update(
            {'class': '', 'placeholder': 'Address'}
        )
        self.fields['town_city'].widget.attrs.update(
            {'class': '', 'placeholder': 'Town/City'}
        )
        self.fields['postcode'].widget.attrs.update(
            {'class': '', 'placeholder': 'Postcode'}
        )

templates/apps/account/dashboard.html
{% extends fnd.main_layout|default:'layouts/upper.html' %}
{% load static %} 
{% load i18n %}


{% block content %}
    <div class="flex col">
        <h1 class="text-color text-center">{% translate "Dashboard" %}</h1>
        <div class="flex justify-center">
            <div class="border border-color radius-2 m-4 p-10">
                <a class="text-decoration-none text-color" href="{% url 'account:orders' %}">{% translate "Orders" %}</a>
            </div>
            
            <div class="border border-color radius-2 m-4 p-10">
                <a class="text-decoration-none text-color" href="{% url 'account:address_list' %}">{% translate "Addresses" %}</a>
            </div>
        </div>
    </div>
{% endblock content %} 

templates/apps/account/orders.html
{% extends fnd.main_layout|default:'layouts/upper.html' %}
{% load static %} 
{% load i18n %}


{% block content %}
    <div class="flex col">
        <h1 class="text-color text-center">{% translate "Orders" %}</h1>
        <div class="flex col">
            <div class="flex mb-4 p-4">
                <div class="flex-1">{% translate "Order.NO" %}</div>
                <div class="flex-1">{% translate "Address" %}</div>
                <div class="flex-1">{% translate "Total" %}</div>
                <div class="flex-1">{% translate "Quantity" %}</div>
                <div class="flex-1">{% translate "Date" %}</div>
            </div>
            {% for order in page_obj %}
                <div class="flex align-center border border-color radius-2 mt-4 p-4">
                    <div class="flex-1">{{ order.order_key }}</div>
                    <div class="flex-1">{{ order.address }}</div>
                    <div class="flex-1">{{ order.total_paid }}</div>
                    <div class="flex-1">{{ order.total_amount }}</div>
                    <div class="flex-1">{{ order.created_at }}</div>
                </div>
            {% endfor %}
            </div>
            {% include 'partials/pagination.html' %}
        </div>
    </div>
{% endblock content %} 

templates/apps/account/passwd_confirm.html
{% extends fnd.main_layout|default:'layouts/upper.html' %}
{% load static %} 
{% load i18n %}


{% block content %}
    <div class="flex justify-center align-center h-vh">
        <div>
            <h1 class="text-color text-center">{% translate "Confirm password" %}</h1>
            <form action="{% url 'account:confirm_passwd_store' %}" method="POST">
                {% csrf_token %}
                {% if form.errors %}
                  {% for field in form %}
                    {% if field.errors %}
                    <div>
                        {{ field.label }}: {{ field.errors|striptags }}
                    </div>
                    {% endif %}
                  {% endfor %}
                {% endif %}

                {{ form.as_p }}
                <div class="text-center mt-4">
                    <button class="border border-color radius-2 px-6 py-4" type="submit">{% translate "Send" %}</button>
                </div>
            </form>
        </div>
    </div>
{% endblock content %} 

templates/apps/account/passwd_reset.html
{% extends fnd.main_layout|default:'layouts/upper.html' %}
{% load static %} 
{% load i18n %}


{% block content %}
    <div class="flex justify-center align-center h-vh">
        <div>
            <h1 class="text-color text-center">{% translate "Reset password" %}</h1>
            <form class="border border-color radius-2 mt-8 p-6" action="{% url 'account:reset_passwd_mail' %}" method="POST">
                {% csrf_token %}
                {% if form.errors %}
                  {% for field in form %}
                    {% if field.errors %}
                    <div>
                        {{ field.label }}: {{ field.errors|striptags }}
                    </div>
                    {% endif %}
                  {% endfor %}
                {% endif %}

                {{ form.as_p }}
                <div class="text-center mt-4">
                    <button class="border border-color radius-2 px-6 py-4" type="submit">{% translate "Send" %}</button>
                </div>
            </form>
        </div>
    </div>
{% endblock content %} 